apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- services.yaml
images:
- name: lw-se-int-esix/esixrepo/my-tweet-app-lacework
  newTag: latest
- name: my-tweet-app
  newName: lw-se-int-esix/esixrepo/my-tweet-app-lacework
  newTag: latest

