name: Deploy my-tweet-app-lacework to GKE
on:
  push:
    branches:
    - main
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: lw-se-int-esix-gke-demo  
  GKE_ZONE: us-central1-c
  DEPLOYMENT_NAME: my-tweet-app
  REGION: us-central1
  ARTIFACT_REGISTRY: lw-se-int-esix/esixrepo



jobs:
  build:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Use Checkout
      uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
       credentials_json: '${{ secrets.GCP_SA_GITHUB }}'
    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Get short SHA
      run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
    - name: Build and push Docker image
      run: |
         gcloud auth configure-docker "us-central1-docker.pkg.dev"
         docker pull "us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:36172ff"
         docker build -t "us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:${{ env.GHA_SHA }}" -t "us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:latest" .
         docker push "us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:latest"
         echo "BUILD : HASH ---   $GHA_SHA"
    # gcloud artifacts docker tags add us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:$env.GHA_SHA us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework:latest
    - name: Scan container images for vulnerabitilies using Lacework
      uses: lacework/lw-scanner-action@v1.2.0 
      with:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        IMAGE_NAME: us-central1-docker.pkg.dev/lw-se-int-esix/esixrepo/my-tweet-app-lacework
        IMAGE_TAG: ${{ env.GHA_SHA }}
        SAVE_RESULTS_IN_LACEWORK: true
        SAVE_BUILD_REPORT: true
        BUILD_REPORT_FILE_NAME: lwreport.html
        SCAN_LIBRARY_PACKAGES: true


